import { ImageMap } from "./types/interfaces";

export const Images : ImageMap = {
    "AllanMunger": require("./../assets/avatars/AllanMunger.png"),
    "AmandaBrady": require("./../assets/avatars/AmandaBrady.png"),
    "AshleyMcCarthy": require("./../assets/avatars/AshleyMcCarthy.png"),
    "CarlosSlattery": require("./../assets/avatars/CarlosSlattery.png"),
    "CarolePoland": require("./../assets/avatars/CarolePoland.png"),
    "CecilFolk": require("./../assets/avatars/CecilFolk.png"),
    "CelesteBurton": require("./../assets/avatars/CelesteBurton.png"),
    "CharlotteWaltson": require("./../assets/avatars/CharlotteWaltson.png"),
    "ColinBallinger": require("./../assets/avatars/ColinBallinger.png"),
    "DaisyPhillips": require("./../assets/avatars/DaisyPhillips.png"),
    "ElliotWoodward": require("./../assets/avatars/ElliotWoodward.png"),
    "ElviaAtkins": require("./../assets/avatars/ElviaAtkins.png"),
    "ErikNason": require("./../assets/avatars/ErikNason.png"),
    "HenryBrill": require("./../assets/avatars/HenryBrill.png"),
    "IsaacFielder": require("./../assets/avatars/IsaacFielder.png"),
    "JohnieMcConnell": require("./../assets/avatars/JohnieMcConnell.png"),
    "KatLarsson": require("./../assets/avatars/Katlarsson.png"),
    "KatriAhokas": require("./../assets/avatars/KatriAhokas.png"),
    "KevinSturgis": require("./../assets/avatars/KevinSturgis.png"),
    "KristinPatterson": require("./../assets/avatars/KristinPatterson.png"),
    "LydiaBauer": require("./../assets/avatars/LydiaBauer.png"),
    "MauricioAugust": require("./../assets/avatars/MauricioAugust.png"),
    "MiguelGarcia": require("./../assets/avatars/MiguelGarcia.png"),
    "MonaKane": require("./../assets/avatars/MonaKane.png"),
    "RobertTolbert": require("./../assets/avatars/RobertTolbert.png"),
    "RobinCounts": require("./../assets/avatars/RobinCounts.png"),
    "TimDeboer": require("./../assets/avatars/TimDeboer.png"),
    "WandaHoward": require("./../assets/avatars/WandaHoward.png")
}